name: Test and Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    name: Run Tests and Check Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Tests with Jacoco
        run: ./gradlew clean test jacocoTestReport

      - name: Post coverage report
        uses: dorny/coverage-comment@v1
        with:
          path: build/reports/jacoco/test/jacocoTestReport.xml
          config: .github/coverage-comment-config.yml